### ISSUE TITLE
Highlight Base, Core and Main?

### ISSUE THREAD

**Issue by randy3k** [JuliaEditorSupport/Julia-sublime#47] opened 2017-03-24 16:10 UTC
```julia
Main.foo()
Base.length()
Core.eval()
```
I guess they should be `support.module` according to the [office docs][1] and there may be missing important modules.

[1]: https://www.sublimetext.com/docs/3/scope_naming.html#variable

**Comment by omus** [comment] 2017-03-24 17:22
`Pkg.add()`

**Comment by ViktorQvarfordt** [comment] 2017-03-24 19:52
Now all built-in modules are scoped with `support.module`. I fetch all built-in modules with
```
filter!(x -> isa(eval(x), Module), [names(Base); names(Core)])
```
Note that `support.module` is usually not highlighted, so this change will not be visible (with the default color scheme).

So far, I do *not* scope `add` in `Pkg.add` with `support.function`. **I wish to discuss this with you:** As I see it, ideally we have, in `Pkg.add()`, that `Pkg` is scoped with `support.module` and `add` is scoped with `support.function`. Similarly for all built-in modules and their built-in functions. The issue is that this leads to lots of special cases (there are 25 built-in modules), could be a mess to maintain. Should this be done or not, what do you think? (Regardless, built-in functions that can be directly used, such as `abs()`, get the scope `support.function`, but if this discussed part is not fixed, then `abs` in `Base.abs()` is *not* scoped with `support.function`.)

---

This also made me realize that `.` was always scoped as an operator. This was wrong, for example in
```
Module.foo()
```
the dot is not an operator, it should not be scoped as such. I've fixed this also, so that  `.` is only scoped as an operator when it acts like an operator, the only case is broadcasting, such as in
```
foo.(vector)
```

**Comment by randy3k** [comment] 2017-03-24 20:44
There are two cases. Consider `M.foo()`

1. `M` is a supported module, but `foo` is not a supported (exported) function, e.g. `Base.process_events()`.
2. `M` is not a supported module, but `foo` is a supported function. E.g.  `DataFrames.length()`.
Though in practice, no one will perform such a call since `length` is available everywhere.
3. Both `M` and `foo` are supported.

I argue that in case 1, it should not be highlighted to indicate that the function is not exported. And in cases 2 and 3, `foo` should be highlighted as `support.function`.

With this logic, 
- the `add` in `Pkg.add()` should not scoped as `support.function`
- `length` in `Base.length()` should scoped as `support function`
- `length` in `DataFrames.length()` should scoped as `support function`


It also raises another issue, consider the followings

```julia
Base.Base64.eval()
#         ^ this is a module
```

But `Base64` is correctly scoped as `variable.function`.

**Comment by ViktorQvarfordt** [comment] 2017-03-25 09:50
> It also raises another issue ...

Yes, I messed up a bit. Fixed now!

How do we know that `length` in `DataFrames.length()` should scoped as support function? `length` is not necessarily available everywhere, and even if it is present, it is not necessarily a built-in.

Right now only supported functions from Base and Core are highlighted only when they are used directly, i.e. as `abs()` but not `Base.abs()`.

**Comment by randy3k** [comment] 2017-03-26 17:46
> 
> How do we know that length in DataFrames.length() should scoped as support function? length is not necessarily available everywhere, and even if it is present, it is not necessarily a built-in.

I think it is generally an error to override built-in functions without proper `import`. It is quite safe to assume that `Module.length()` is `Base.length()`

```julia
julia> type A end

julia> length(a::A) = 1
length (generic function with 1 method)

julia> length([1,2,3])
ERROR: MethodError: no method matching length(::Array{Int64,1})
you may have intended to import Base.length
Closest candidates are:
  length(::A) at REPL[2]:1
```

**Comment by ViktorQvarfordt** [comment] 2017-03-27 10:57
I agree, but we are highlighting `length()` right now, but not `SomeModule.length()`. Whether or not `SomeModule` contains the method `length` cannot be known by the syntax highlighter. I don't see how we can improve this further.

**Comment by randy3k** [comment] 2017-03-27 13:06
That is why I said they are available everywhere.

```
julia> module A end
A

julia> A.length([1,2,3])
3

```

**Comment by ViktorQvarfordt** [comment] 2017-03-27 14:19
Aha, ok! So, how do we get a list of these always-present-methods? To extract the methods from `Base` I do `names(Base)`. However,
```
julia> module A end
A

julia> names(A)
1-element Array{Symbol,1}:
 :A

julia> names(A, true, true)
5-element Array{Symbol,1}:
 Symbol("#eval")
 :A             
 :Any           
 :Tuple         
 :eval          
```

**Comment by randy3k** [comment] 2017-03-27 14:56
I guess we should only scope the exported functions.

**Comment by ViktorQvarfordt** [comment] 2017-03-27 16:09
So, no further changes?

**Comment by randy3k** [comment] 2017-03-27 19:24
The only thing that I can think of now is the scope of `A.length()` as the function `A.length` is the same as `Base.length`.

<img width="225" alt="screen shot 2017-03-27 at 3 22 10 pm" src="https://cloud.githubusercontent.com/assets/1690993/24373950/2e2879e2-1301-11e7-91ee-0eab6392a898.png">

**Comment by ViktorQvarfordt** [comment] 2017-03-28 16:05
This discussion has shown that we want to be ambitious. This commit goes all the ways. `Base.abs` is highlighted as well as `abs`, also `Pkg.add` is highlighted. I do like python, I highlight both `length` and `length()` as `support.function`, of course only the latter has `meta.function-call`. Re-open if I missed anything.

**Closed by ViktorQvarfordt** 2017-03-28 16:05 UTC

**Comment by randy3k** [comment] 2017-03-28 16:23
It would be nice to have a script to generate the the syntax file programmatically.

**Comment by ViktorQvarfordt** [comment] 2017-03-28 17:16
I have included the code I used to fetch exported functions etc. in comments in the syntax file. See for example https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Julia.sublime-syntax#L31. Is this what you mean?

**Comment by randy3k** [comment] 2017-03-28 18:10
I meant a script to load the `.sublime-syntax` and replace those lines directly. I thought about using [YAML.jl][1], but all the comments may be lost.

[1]: https://github.com/dcjones/YAML.jl

**Comment by ViktorQvarfordt** [comment] 2017-03-28 19:15
Cool idea! In the current state this might add more complexity than needed though. I'd prefer to keep it simple. However, if we get more and more generated regexes, going this route would be nice. At some stage one might even want to have auto completion for built-in functions and packages, with built in documentation for function call parameters etc. Something IDE-like. Perhaps as a separate package though, not everyone wants this from a syntax highlighting package. Maybe such IDE packages already exist, maybe one can build on sublime code intel or similar
